# Generated by Django 5.1.2 on 2025-06-15 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_homepage_delete_contact_delete_testimonial_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='facbook_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='instagram_link',
            field=models.URLField(blank=True),
        ),
    ]
