# Generated by Django 5.1.2 on 2025-06-15 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_homepage_facbook_link_homepage_instagram_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='aboute_title',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='subtitle',
        ),
        migrations.AddField(
            model_name='homepage',
            name='about_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='home/'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='facbook_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='instagram_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
