# Generated by Django 5.1.2 on 2025-06-15 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_homepage_aboute_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
